if ( 
         || req.http.user-agent ~ "Aboundex"
  || req.http.user-agent ~ "libssh2"
  || req.http.user-agent ~ "80legs"
  || req.http.user-agent ~ "360Spider"
  || req.http.user-agent ~ "Java"
  || req.http.user-agent ~ "Cogentbot"
  || req.http.user-agent ~ "Alexibot"
  || req.http.user-agent ~ "asterias"
  || req.http.user-agent ~ "attach"
  || req.http.user-agent ~ "BackDoorBot"
  || req.http.user-agent ~ "BackWeb"
  || req.http.user-agent ~ "Bandit"
  || req.http.user-agent ~ "BatchFTP"
  || req.http.user-agent ~ "Bigfoot"
  || req.http.user-agent ~ "Black.Hole"
  || req.http.user-agent ~ "BlackWidow"
  || req.http.user-agent ~ "BlowFish"
  || req.http.user-agent ~ "BotALot"
  || req.http.user-agent ~ "Buddy"
  || req.http.user-agent ~ "BuiltBotTough"
  || req.http.user-agent ~ "Bullseye"
  || req.http.user-agent ~ "BunnySlippers"
  || req.http.user-agent ~ "Cegbfeieh"
  || req.http.user-agent ~ "CheeseBot"
  || req.http.user-agent ~ "CherryPicker"
  || req.http.user-agent ~ "ChinaClaw"
  || req.http.user-agent ~ "Collector"
  || req.http.user-agent ~ "Copier"
  || req.http.user-agent ~ "CopyRightCheck"
  || req.http.user-agent ~ "cosmos"
  || req.http.user-agent ~ "Crescent"
  || req.http.user-agent ~ "Custo"
  || req.http.user-agent ~ "AIBOT"
  || req.http.user-agent ~ "DISCo"
  || req.http.user-agent ~ "DIIbot"
  || req.http.user-agent ~ "DittoSpyder"
  || req.http.user-agent ~ "Download\ Demon"
  || req.http.user-agent ~ "Download\ Devil"
  || req.http.user-agent ~ "Download\ Wonder"
  || req.http.user-agent ~ "dragonfly"
  || req.http.user-agent ~ "Drip"
  || req.http.user-agent ~ "eCatch"
  || req.http.user-agent ~ "EasyDL"
  || req.http.user-agent ~ "ebingbong"
  || req.http.user-agent ~ "EirGrabber"
  || req.http.user-agent ~ "EmailCollector"
  || req.http.user-agent ~ "EmailSiphon"
  || req.http.user-agent ~ "EmailWolf"
  || req.http.user-agent ~ "EroCrawler"
  || req.http.user-agent ~ "Exabot"
  || req.http.user-agent ~ "Express\ WebPictures"
  || req.http.user-agent ~ "Extractor"
  || req.http.user-agent ~ "EyeNetIE"
  || req.http.user-agent ~ "Foobot"
  || req.http.user-agent ~ "flunky"
  || req.http.user-agent ~ "FrontPage"
  || req.http.user-agent ~ "Go-Ahead-Got-It"
  || req.http.user-agent ~ "gotit"
  || req.http.user-agent ~ "GrabNet"
  || req.http.user-agent ~ "Grafula"
  || req.http.user-agent ~ "Harvest"
  || req.http.user-agent ~ "hloader"
  || req.http.user-agent ~ "HMView"
  || req.http.user-agent ~ "HTTrack"
  || req.http.user-agent ~ "humanlinks"
  || req.http.user-agent ~ "IlseBot"
  || req.http.user-agent ~ "Image\ Stripper"
  || req.http.user-agent ~ "Image\ Sucker"
  || req.http.user-agent ~ "Indy\ Library"
  || req.http.user-agent ~ "InfoNaviRobot"
  || req.http.user-agent ~ "InfoTekies"
  || req.http.user-agent ~ "Intelliseek"
  || req.http.user-agent ~ "InterGET"
  || req.http.user-agent ~ "Internet\ Ninja"
  || req.http.user-agent ~ "Jakarta"
  || req.http.user-agent ~ "JennyBot"
  || req.http.user-agent ~ "JetCar"
  || req.http.user-agent ~ "JustView"
  || req.http.user-agent ~ "Jyxobot"
  || req.http.user-agent ~ "Kenjin.Spider"
  || req.http.user-agent ~ "Keyword.Density"
  || req.http.user-agent ~ "larbin"
  || req.http.user-agent ~ "LexiBot"
  || req.http.user-agent ~ "libWeb/clsHTTP"
  || req.http.user-agent ~ "LinkextractorPro"
  || req.http.user-agent ~ "LinkScan/8.1a.Unix"
  || req.http.user-agent ~ "LNSpiderguy"
  || req.http.user-agent ~ "LinkWalker"
  || req.http.user-agent ~ "lwp-trivial"
  || req.http.user-agent ~ "LWP::Simple"
  || req.http.user-agent ~ "Magnet"
  || req.http.user-agent ~ "Mag-Net"
  || req.http.user-agent ~ "MarkWatch"
  || req.http.user-agent ~ "Mass\ Downloader"
  || req.http.user-agent ~ "Mata.Hari"
  || req.http.user-agent ~ "Microsoft.URL"
  || req.http.user-agent ~ "Microsoft\ URL\ Control"
  || req.http.user-agent ~ "MIDown\ tool"
  || req.http.user-agent ~ "MIIxpc"
  || req.http.user-agent ~ "Mirror"
  || req.http.user-agent ~ "Missigua\ Locator"
  || req.http.user-agent ~ "Mister\ PiX"
  || req.http.user-agent ~ "moget"
  || req.http.user-agent ~ "NAMEPROTECT"
  || req.http.user-agent ~ "Navroad"
  || req.http.user-agent ~ "NearSite"
  || req.http.user-agent ~ "NetAnts"
  || req.http.user-agent ~ "Netcraft"
  || req.http.user-agent ~ "NetMechanic"
  || req.http.user-agent ~ "NetSpider"
  || req.http.user-agent ~ "Net\ Vampire"
  || req.http.user-agent ~ "NetZIP"
  || req.http.user-agent ~ "NextGenSearchBot"
  || req.http.user-agent ~ "NICErsPRO"
  || req.http.user-agent ~ "niki-bot"
  || req.http.user-agent ~ "NimbleCrawler"
  || req.http.user-agent ~ "Ninja"
  || req.http.user-agent ~ "NPbot"
  || req.http.user-agent ~ "Octopus"
  || req.http.user-agent ~ "Offline\ Explorer"
  || req.http.user-agent ~ "Offline\ Navigator"
  || req.http.user-agent ~ "Openfind"
  || req.http.user-agent ~ "OutfoxBot"
  || req.http.user-agent ~ "PageGrabber"
  || req.http.user-agent ~ "Papa\ Foto"
  || req.http.user-agent ~ "pavuk"
  || req.http.user-agent ~ "PHP\ version\ tracker"
  || req.http.user-agent ~ "Pockey"
  || req.http.user-agent ~ "ProPowerBot/2.14"
  || req.http.user-agent ~ "ProWebWalker"
  || req.http.user-agent ~ "psbot"
  || req.http.user-agent ~ "Pump"
  || req.http.user-agent ~ "QueryN.Metasearch"
  || req.http.user-agent ~ "RealDownload"
  || req.http.user-agent ~ "Reaper"
  || req.http.user-agent ~ "Recorder"
  || req.http.user-agent ~ "ReGet"
  || req.http.user-agent ~ "RepoMonkey"
  || req.http.user-agent ~ "Siphon"
  || req.http.user-agent ~ "SiteSnagger"
  || req.http.user-agent ~ "SlySearch"
  || req.http.user-agent ~ "SmartDownload"
  || req.http.user-agent ~ "Snake"
  || req.http.user-agent ~ "Snapbot"
  || req.http.user-agent ~ "Snoopy"
  || req.http.user-agent ~ "sogou"
  || req.http.user-agent ~ "SpaceBison"
  || req.http.user-agent ~ "SpankBot"
  || req.http.user-agent ~ "spanner"
  || req.http.user-agent ~ "Sqworm"
  || req.http.user-agent ~ "Stripper"
  || req.http.user-agent ~ "Sucker"
  || req.http.user-agent ~ "SuperBot"
  || req.http.user-agent ~ "SuperHTTP"
  || req.http.user-agent ~ "Surfbot"
  || req.http.user-agent ~ "suzuran"
  || req.http.user-agent ~ "Szukacz/1.4"
  || req.http.user-agent ~ "tAkeOut"
  || req.http.user-agent ~ "Teleport"
  || req.http.user-agent ~ "Telesoft"
  || req.http.user-agent ~ "TurnitinBot/1.5"
  || req.http.user-agent ~ "The.Intraformant"
  || req.http.user-agent ~ "TheNomad"
  || req.http.user-agent ~ "TightTwatBot"
  || req.http.user-agent ~ "Titan"
  || req.http.user-agent ~ "True_Robot"
  || req.http.user-agent ~ "turingos"
  || req.http.user-agent ~ "TurnitinBot"
  || req.http.user-agent ~ "URLy.Warning"
  || req.http.user-agent ~ "Vacuum"
  || req.http.user-agent ~ "VoidEYE"
  || req.http.user-agent ~ "Web\ Image\ Collector"
  || req.http.user-agent ~ "Web\ Sucker"
  || req.http.user-agent ~ "WebAuto"
  || req.http.user-agent ~ "WebBandit"
  || req.http.user-agent ~ "Webclipping.com"
  || req.http.user-agent ~ "WebCopier"
  || req.http.user-agent ~ "WebEMailExtrac.*"
  || req.http.user-agent ~ "WebEnhancer"
  || req.http.user-agent ~ "WebFetch"
  || req.http.user-agent ~ "WebGo\ IS"
  || req.http.user-agent ~ "Web.Image.Collector"
  || req.http.user-agent ~ "WebLeacher"
  || req.http.user-agent ~ "WebmasterWorldForumBot"
  || req.http.user-agent ~ "WebReaper"
  || req.http.user-agent ~ "WebSauger"
  || req.http.user-agent ~ "Website\ eXtractor"
  || req.http.user-agent ~ "Website\ Quester"
  || req.http.user-agent ~ "Webster"
  || req.http.user-agent ~ "WebStripper"
  || req.http.user-agent ~ "WebWhacker"
  || req.http.user-agent ~ "WebZIP"
  || req.http.user-agent ~ "Whacker"
  || req.http.user-agent ~ "Widow"
  || req.http.user-agent ~ "WISENutbot"
  || req.http.user-agent ~ "WWWOFFLE"
  || req.http.user-agent ~ "WWW-Collector-E"
  || req.http.user-agent ~ "Xaldon"
  || req.http.user-agent ~ "Xenu"
  || req.http.user-agent ~ "Zeus"
  || req.http.user-agent ~ "ZmEu"
  || req.http.user-agent ~ "Zyborg"
  || req.http.user-agent ~ "Acunetix"
  || req.http.user-agent ~ "FHscan"
  || req.http.user-agent ~ "Baiduspider"
  || req.http.user-agent ~ "Nutch-"
  || req.http.user-agent ~ "IDBot"
  || req.http.user-agent ~ "id-search"
  || req.http.user-agent ~ "MJ12bot"
  || req.http.user-agent ~ "ConveraCrawler"
  || req.http.user-agent ~ "MFC_Tear_Sample"
  || req.http.user-agent ~ "HTTP::Lite"
  || req.http.user-agent ~ "PHPCrawl"
  || req.http.user-agent ~ "URI::Fetch"
  || req.http.user-agent ~ "http client"
  || req.http.user-agent ~ "PECL::HTTP"
  || req.http.user-agent ~ "panscient.com"
  || req.http.user-agent ~ "IBM EVV"
  || req.http.user-agent ~ "Bork-edition"
  || req.http.user-agent ~ "Fetch API Request"
  || req.http.user-agent ~ "PleaseCrawl"
  || req.http.user-agent ~ "layeredtech.com"
  || req.http.user-agent ~ "WEP Search"
  || req.http.user-agent ~ "Wells Search II"
  || req.http.user-agent ~ "Missigua Locator"
  || req.http.user-agent ~ "ISC Systems iRc Search"
  || req.http.user-agent ~ "Microsoft URL Control"
  || req.http.user-agent ~ "AhrefsBot"
  || req.http.user-agent ~ "Indy Library"
  || req.http.user-agent ~ "Boston Project"
  || req.http.user-agent ~ "Atomic_Email_Hunter"
  || req.http.user-agent ~ "atSpider"
  || req.http.user-agent ~ "autoemailspider"
  || req.http.user-agent ~ "China Local Browse"
  || req.http.user-agent ~ "ContactBot"
  || req.http.user-agent ~ "ContentSmartz"
  || req.http.user-agent ~ "DataCha0s"
  || req.http.user-agent ~ "Demo Bot"
  || req.http.user-agent ~ "DSurf15a"
  || req.http.user-agent ~ "Educate Search"
  || req.http.user-agent ~ "EmailWolf"
  || req.http.user-agent ~ "ESurf15a"
  || req.http.user-agent ~ "ExtractorPro"
  || req.http.user-agent ~ "Franklin Locator"
  || req.http.user-agent ~ "Full Web Bot"
  || req.http.user-agent ~ "Guestbook Auto Submitter"
  || req.http.user-agent ~ "Industry Program"
  || req.http.user-agent ~ "Research Bot"
  || req.http.user-agent ~ "LARBIN-EXPERIMENTAL"
  || req.http.user-agent ~ "LetsCrawl.com"
  || req.http.user-agent ~ "Lincoln State Web Browser"
  || req.http.user-agent ~ "LMQueueBot"
  || req.http.user-agent ~ "LWP::Simple"
  || req.http.user-agent ~ "Mac Finder"
  || req.http.user-agent ~ "Foundation Class Library"
  || req.http.user-agent ~ "Missouri"
  || req.http.user-agent ~ "Mizzu Labs"
  || req.http.user-agent ~ "Mo College"
  || req.http.user-agent ~ "Email Extractor"
  || req.http.user-agent ~ "Iplexx Spider"
  || req.http.user-agent ~ "MVAClient"
  || req.http.user-agent ~ "NameOfAgent"
  || req.http.user-agent ~ "NASA Search"
  || req.http.user-agent ~ "PEval 1"
  || req.http.user-agent ~ "Production Bot"
  || req.http.user-agent ~ "Program Shareware"
  || req.http.user-agent ~ "PSurf15a"
  || req.http.user-agent ~ "psycheclone"
  || req.http.user-agent ~ "RSurf15a"
  || req.http.user-agent ~ "ShablastBot"
  || req.http.user-agent ~ "snap.com beta crawler"
  || req.http.user-agent ~ "Sogou develop spider"
  || req.http.user-agent ~ "Sogou Orion spider"
  || req.http.user-agent ~ "sogou spider"
  || req.http.user-agent ~ "Sogou web spider"
  || req.http.user-agent ~ "SSurf15a"
  || req.http.user-agent ~ "Under the Rainbow"
  || req.http.user-agent ~ "VadixBot"
  || req.http.user-agent ~ "libwww-perl"
  || req.http.user-agent ~ "aiHitBot"
  || req.http.user-agent ~ "betaBot"
  || req.http.user-agent ~ "Bolt"
  || req.http.user-agent ~ "BLEXBot"
  || req.http.user-agent ~ "BUbiNG"
  || req.http.user-agent ~ "CazoodleBot"
  || req.http.user-agent ~ "CPython"
  || req.http.user-agent ~ "CCBot"
  || req.http.user-agent ~ "Curious"
  || req.http.user-agent ~ "CRAZYWEBCRAWLER"
  || req.http.user-agent ~ "FlashGet"
  || req.http.user-agent ~ "Findxbot"
  || req.http.user-agent ~ "GetRight"
  || req.http.user-agent ~ "GetWeb!"  1;
  || req.http.user-agent ~ "ia_archiver"
  || req.http.user-agent ~ "InternetSeer"
  || req.http.user-agent ~ "IRLbot"
  || req.http.user-agent ~ "LeechFTP"
  || req.http.user-agent ~ "Lightspeedsystems"
  || req.http.user-agent ~ "litemage_walker"
  || req.http.user-agent ~ "LinksManager"
  || req.http.user-agent ~ "Lipperhey"
  || req.http.user-agent ~ "ltx71"
  || req.http.user-agent ~ "Maxthon"
  || req.http.user-agent ~ "Mail.RU_Bot"
  || req.http.user-agent ~ "MegaIndex"
  || req.http.user-agent ~ "meanpathbot"
  || req.http.user-agent ~ "Microsoft-IIS"
  || req.http.user-agent ~ "MSFrontPage"
  || req.http.user-agent ~ "FastProbe"
  || req.http.user-agent ~ "Nutch"
  || req.http.user-agent ~ "PeoplePal"
  || req.http.user-agent ~ "Pi-Monster"
  || req.http.user-agent ~ "prijsbest"
  || req.http.user-agent ~ "python-requests"
  || req.http.user-agent ~ "Qwantify"
  || req.http.user-agent ~ "RedesScrapy"
  || req.http.user-agent ~ "Rippers"
  || req.http.user-agent ~ "RocketCrawler"
  || req.http.user-agent ~ "SBIder"
  || req.http.user-agent ~ "Screaming"
  || req.http.user-agent ~ "ScreenerBot"
  || req.http.user-agent ~ "SEOprofiler"
  || req.http.user-agent ~ "SeaMonkey"
  || req.http.user-agent ~ "SeznamBot"
  || req.http.user-agent ~ "sitecheck.internetseer.com"
  || req.http.user-agent ~ "SputnikBot"
  || req.http.user-agent ~ "Steeler"
  || req.http.user-agent ~ "sqlmap"
  || req.http.user-agent ~ "Toata"
  || req.http.user-agent ~ "TwengaBot"
  || req.http.user-agent ~ "Typhoeus"
  || req.http.user-agent ~ "voltron"
  || req.http.user-agent ~ "Vagabondo"
  || req.http.user-agent ~ "Visbot"
  || req.http.user-agent ~ "webalta"
  || req.http.user-agent ~ "ZyBorg"
  || req.http.user-agent ~ "VB Project"
  || req.http.user-agent ~ "masscan"
  || req.http.user-agent ~ "muhstik"
  || req.http.user-agent ~ "zgrab"
  || req.http.user-agent ~ "checker"
  || req.http.user-agent ~ "Netcraft"
  || req.http.user-agent ~ "pdrlabs"
  || req.http.user-agent ~ "DotBot"
  || req.http.user-agent ~ "Python-urllib"
  || req.http.user-agent ~ "netEstate"
  || req.http.user-agent ~ "GrapeshotCrawler"
  || req.http.user-agent ~ "mappydata"
  || req.http.user-agent ~ "Cliqzbot"
  || req.http.user-agent ~ "spbot"
  || req.http.user-agent ~ "Dataprovider"
  || req.http.user-agent ~ "getroot"
  || req.http.user-agent ~ "evc-batch"
  || req.http.user-agent ~ "DomainSigmaCrawler"
  || req.http.user-agent ~ "HttpClient"
  || req.http.user-agent ~ "Auto Spider"
  || req.http.user-agent ~ "Go-http-client" 
  || req.http.user-agent ~ "BDCbot"
  || req.http.user-agent ~ "node-fetch"
  || req.http.user-agent ~ "Wotbox"
  || req.http.user-agent ~ "DomainCrawler"
  || req.http.user-agent ~ "Barkrowler"
  || req.http.user-agent ~ "WebCrawler"
  || req.http.user-agent ~ "SafeDNSBot"
  || req.http.user-agent ~ "\/bin\/bash"
  || req.http.user-agent ~ "sysscan"
  || req.http.user-agent ~ "Uptimebot"
  || req.http.user-agent ~ "AwarioRssBot"
  || req.http.user-agent ~ "MSDN SurfBear"
  || req.http.user-agent ~ "ExtLinksBot"
  || req.http.user-agent ~ "filterdb"
  || req.http.user-agent ~ "uCrawler"
  || req.http.user-agent ~ "libwww-FM"
  || req.http.user-agent ~ "Streamline3Bot"
  || req.http.user-agent ~ "Exabot"
  || req.http.user-agent ~ "crawler4j"
  || req.http.user-agent ~ "DomainStatsBot"
  || req.http.user-agent ~ "Yeti"
  || req.http.user-agent ~ "BacklinkCrawler"
  || req.http.user-agent ~ "avantbrowser"
  || req.http.user-agent ~ "Mechanize"
  || req.http.user-agent ~ "JDatabaseDriverMysqli"
  || req.http.user-agent ~ "NetpeakSpiderBot"
  || req.http.user-agent ~ "scanner"
  || req.http.user-agent ~ "probethenet"
  || req.http.user-agent ~ "Digincore"
  || req.http.user-agent ~ "Hstpnetwork"
  || req.http.user-agent ~ "WinHttpRequest"
  || req.http.user-agent ~ "WeCrawlForThePeace"
  || req.http.user-agent ~ "Wappalyzer"
  || req.http.user-agent ~ "httpscheck"
  || req.http.user-agent ~ "Scrapy"
  || req.http.user-agent ~ "Plukkie"
  || req.http.user-agent ~ "techleadzbot"
  || req.http.user-agent ~ "TweetmemeBot"
  || req.http.user-agent ~ "Symfony"
  || req.http.user-agent ~ "CATExplorador"
  || req.http.user-agent ~ "magereport"
  || req.http.user-agent ~ "SnowHaze"
  || req.http.user-agent ~ "AlphaBot"
  || req.http.user-agent ~ "informatik"
  || req.http.user-agent ~ "MauiBot"
  || req.http.user-agent ~ "Crawler;"
  || req.http.user-agent ~ "rogerbot;"
  || req.http.user-agent ~ "Pierre Smith"
  || req.http.user-agent ~ "GreenBrowser"
  || req.http.user-agent ~ "scraper"
  || req.http.user-agent ~ "PATHspider"
  || req.http.user-agent ~ "tracemyfile"
  || req.http.user-agent ~ "russia"
  || req.http.user-agent ~ "Linguee"
  || req.http.user-agent ~ "tomnomnom"
  || req.http.user-agent ~ "StormCrawlera"
  || req.http.user-agent ~ "similartech"
  || req.http.user-agent ~ "serpstatbot"
  || req.http.user-agent ~ "DivulgaMais"
  || req.http.user-agent ~ "CheckMarkNetwork"
  || req.http.user-agent ~ "gobuster"
  || req.http.user-agent ~ "Jersey"
  || req.http.user-agent ~ "Apache-HttpClient"
  || req.http.user-agent ~ "ProxyChecker"
  || req.http.user-agent ~ "spider"
  || req.http.user-agent ~ "Jorgee"
  || req.http.user-agent ~ "Hakai"
  || req.http.user-agent ~ "PowerShell"
  || req.http.user-agent ~ "kubectl"
  || req.http.user-agent ~ "Scanner"
  || req.http.user-agent ~ "ApiTool"
  || req.http.user-agent ~ "LinkpadBot"

     ) {
         error 405 "BL BT";
    }
